### ISSUE TITLE
Can reactify be moved to devDependencies?

### ISSUE THREAD

**Issue by detj** [yuanyan/react-image#2]
Since, `reactify` is only being used in the gulpfile. I think it can be safely moved to `devDependencies`. That would save the unnecessary download on `NODE_ENV=production`. 

Possible? Let me know, I'll send PR.

**Comment by mbrevda** [comment]
This project has been superseded by https://github.com/mbrevda/react-image. Please give it a try and see if your issues are solved!

**Comment by detj** [comment]
Cool, thanks!
