### ISSUE TITLE
Project merge?

### ISSUE THREAD

**Issue by mbrevda** [yuanyan/react-image#3]
I've noticed that we both have packages that address image loading in React. It is often a burden to maintain open source software and it looks like your last update to react-image has been more than two years ago. As I also have an image loader, I would like to propose a merger between the two projects, which can lead to great useage and consolidated and simpler support.  We can continue distributing under the name react-image, allowing you to collaborate on the new project or allocate more resources to your other projects.

Which features of react-image do you find particularly important? I was hoping we can release the next major based on react-img-multi, with support for the core feature set of react-image. I'll gladly try to incorporate those into react-img-multi.

Here is a link to react-img-multi for you to review. Let me know what you think?

https://github.com/mbrevda/react-img-multi

Looking forward!

**Comment by yuanyan** [comment]
OK，your could release next major version based on react-img-multi.

**Comment by mbrevda** [comment]
Awesome, Ill have the next version available soon!
